# ./docker-compose.yml
version: '3'

services:
  nginx:
    build: ./proxy
    container_name: nginx
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    ports:
      - 80:80
      - 443:443

