# ./docker-compose.yml
version: '3'

services:
  nginx:
    build: ./proxy
    container_name: nginx
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    ports:
      - 80:80
      - 443:443
    links:
      - openhab-alexa
    depends_on:
      - openhab-alexa

  openhab-alexa:
    build: ./openhab-alexa
    container_name: openhab-alexa

