# ./docker-compose.yml
version: '3'

services:
  nginx-proxy:
    container_name: nginx-proxy
    build: ./proxy
    image: titan:5000/nginx-proxy
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    ports:
      - 80:80
      - 443:443
    links:
      - openhab-alexa
    depends_on:
      - openhab-alexa

  openhab-alexa:
    build: ./openhab-alexa
    container_name: openhab-alexa
    image: titan:5000/openhab-alexa
    ports:
      - 8888:8080
